application: i-portfolio-706
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
  
- url: /static
  static_dir: ./workforce/static

- url: /.*
  script: main.application
  
libraries:
- name: django
  version: "1.5"

env_variables:
  DJANGO_SETTINGS_MODULE: 'workforce.settings'